project:
  type: book
  post-render:
    - _post_zipdata.R

book:
  title: "R语言空间数据分析入门教程"
  author: "HPDell"
  date: "1/19/2019"
  chapters:
    - index.qmd
    - 01-数据读写.qmd
    - 02-数据预处理.qmd
    - 03-数据可视化.qmd
    - 04-数据分析.qmd

format:
  html:
    theme: cosmo
    resources: 
      - "data/*"

lang: zh

execute: 
  freeze: auto
