project:
  type: book
  post-render:
    - _post_zipdata.R

book:
  title: "R语言空间数据分析入门教程"
  author: "HPDell"
  date: "1/19/2019"
  chapters:
    - index.qmd
    - 01-数据读写.qmd
    - 02-数据预处理.qmd
    - 03-数据可视化.qmd
    - 04-数据分析.qmd

comments: 
  giscus: 
    repo: hpdell/RTraining
    repo-id: R_kgDOJ1O3-Q
    category: Comments
    category-id: DIC_kwDOJ1O3-c4CXiX-
    mapping: title
    input-position: top
    language: zh-CN
    reactions-enabled: true

format:
  html:
    theme: cosmo
    resources: 
      - "data/*"

lang: zh

execute: 
  freeze: auto
